# Dot Product

Dot product (czyli iloczyn skalarny) to jedna z najważniejszych operacji matematycznych w całej algebrze liniowej i absolutny fundament sztucznej inteligencji.

W najprostszym ujęciu jest to operacja, która bierze dwa ciągi liczb (wektory) o tej samej długości, mnoży przez siebie odpowiadające im elementy, a na koniec sumuje te wyniki w jedną pojedynczą liczbę (skalar).

$$a \cdot b = (a_1 \times b_1) + (a_2 \times b_2) + \dots + (a_n \times b_n)$$

## Dlaczego potrzebowaliśmy "transpose"?

Kiedy przechodzimy z pojedynczych wektorów na całe macierze (tablice 2D), dot product staje się mnożeniem macierzy.

Zasada jest tutaj ściśle określona: mnożysz wiersze pierwszej macierzy przez kolumny drugiej macierzy. Aby to było fizycznie możliwe, liczba elementów w wierszu pierwszej macierzy musi być identyczna z liczbą elementów w kolumnie drugiej macierzy.Mówiąc językiem kształtów (wymiarów): macierz o wymiarach $M \times N$ można pomnożyć przez dot product tylko z macierzą o wymiarach $N \times P$. 

Wewnętrzne wymiary ($N$) muszą się zgadzać.

Wynikiem będzie nowa macierz o wymiarach $M \times P$.

### AI tłumaczy: 

In [47]:
import numpy as np

# Nasze wektory opisują 3 cechy: [Akcja, Komedia, Sci-Fi]

# Użytkownik bardzo lubi Akcję (5) i Sci-Fi (4), ale nie znosi Komedii (0)
uzytkownik = np.array([5, 0, 4])

# Profilujemy nasze filmy (1 oznacza, że film ma tę cechę, 0 że nie ma)
matrix = np.array([1, 0, 1])         # Akcja + Sci-Fi
kac_vegas = np.array([0, 1, 0])      # Tylko Komedia
men_in_black = np.array([1, 1, 1])   # Akcja + Komedia + Sci-Fi

# Obliczamy podobieństwo używając dot product
wynik_matrix = np.dot(uzytkownik, matrix)
wynik_kac_vegas = uzytkownik @ kac_vegas        # używamy operatora @ (to samo co np.dot)
wynik_men_in_black = uzytkownik @ men_in_black

print(f"Dopasowanie dla Matrixa: {wynik_matrix}")
print(f"Dopasowanie dla Kac Vegas: {wynik_kac_vegas}")
print(f"Dopasowanie dla Men in Black: {wynik_men_in_black}")

Dopasowanie dla Matrixa: 9
Dopasowanie dla Kac Vegas: 0
Dopasowanie dla Men in Black: 9


## Dot product

In [7]:
np.random.seed(42)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [44]:
mat1

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [45]:
mat2

array([[4, 1, 7],
       [5, 1, 4],
       [0, 9, 5],
       [8, 0, 9],
       [2, 6, 3]])

In [51]:
wynik = np.dot(mat1, mat2)  # we have error here
# we must have same values in the middle
# in this case (3, 3) or (5, 5) 


ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [59]:
#Transporting mat2
mat2T = np.transpose(mat2)
mat2T

array([[4, 5, 0, 8, 2],
       [1, 1, 9, 0, 6],
       [7, 4, 5, 9, 3]])

In [60]:
# dot product 
wynik = np.dot(mat1, mat2T)
wynik
#np.shape(mat1), np.shape(mat2T) 

array([[ 76,  61,  62, 111,  51],
       [ 85,  62,  99, 113,  71],
       [ 63,  44,  89,  79,  61],
       [ 68,  51,  62,  95,  47],
       [ 65,  57,  43, 101,  41]])

In [61]:
wynik.shape

(5, 5)

## Dot Product prostszy przykład: 

In [15]:
A = np.array([[1, 2],
              [3, 5]])

B = np.array([[10, 10],
              [10, 10]])
     
np.dot(A, B)   # (Tak samo się liczyło na Algebrze liniowej 1)  -->  |       -->  |
#                                                                    |   +        |
#                                                                    \/           \/

array([[30, 30],
       [80, 80]])

## Hadamard product  - zwykłe mnożenie 

Iloczyn Hadamarda to intuicyjny sposób mnożenia dwóch macierzy lub wektorów. Polega na mnożeniu ich po prostu element przez element

W bibliotece NumPy iloczyn Hadamarda to po prostu zwykły znak mnożenia * (lub funkcja np.multiply())

AI PRZYKŁAD:

In [18]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[10, 10],
              [10, 10]])

# Iloczyn Hadamarda (element przez element)
wynik_hadamard = A * B
wynik_hadamard

array([[10, 20],
       [30, 40]])

In [66]:
print()
print()
print()
print()

# Exercise