# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [42]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array ([1, 2, 3])
a1
# Create a 2-dimensional NumPy array using np.array()
a2 = np.array ([[1, 2, 3], [4, 5, 6]])
a2.ndim

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array ([[[1, 2, 3], 
                 [4, 5, 6],
                 [7, 8, 9]],
                
                [[11, 12, 13], 
                 [14, 15, 16],
                 [17, 18, 19]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [27]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(f"""Array 1
number of dimensions: {a1.ndim}
data type: {a1.dtype}
size: {a1.size}
type: {type(a1)}
""")

Array 1
number of dimensions: 1
data type: int64
size: 3
type: <class 'numpy.ndarray'>



In [28]:
# Attributes of 2-dimensional array
print(f"""Array 2
number of dimensions: {a2.ndim}
data type: {a2.dtype}
size: {a2.size}
type: {type(a2)}
""")

Array 2
number of dimensions: 2
data type: int64
size: 6
type: <class 'numpy.ndarray'>



In [29]:
# Attributes of 3-dimensional array
print(f"""Array 3
number of dimensions: {a3.ndim}
data type: {a3.dtype}
size: {a3.size}
type: {type(a3)}
""")

Array 3
number of dimensions: 3
data type: int64
size: 18
type: <class 'numpy.ndarray'>



In [49]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

# df = pd.DataFrame(a1)  # ARRAY 1
df = pd.DataFrame(a2)  #  ARRAY 2
df





,0,1,2
0,1,2,3
1,4,5,6


In [51]:
# Create an array of shape (10, 2) with only ones
np.ones((10, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [52]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7, 2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [56]:
# Create an array within a range of 0 and 100 with step 3
array1 = np.arange(0, 100, 3)
array1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [59]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array2 = np.random.randint(0, 11, size=(7, 2))
array2

array([[ 5,  5],
       [ 1,  9],
       [ 5,  6],
       [ 5, 10],
       [ 1,  2],
       [ 6, 10],
       [ 1,  3]])

In [64]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array3 = np.random.random_sample((3,5))
array3

array([[0.33663333, 0.49988241, 0.35638783, 0.71588226, 0.75959084],
       [0.5571715 , 0.82051102, 0.3990043 , 0.23994378, 0.59445978],
       [0.51817131, 0.18446215, 0.78268218, 0.56117713, 0.47658425]])

In [71]:
# Set the random seed to 42
seed = np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
array4 = np.random.randint(0, 11, size=(4, 6))
array4

array([[ 6,  3, 10,  7,  4,  6],
       [ 9,  2,  6, 10, 10,  7],
       [ 4,  3,  7,  7,  2,  5],
       [ 4,  1,  7,  5,  1,  4]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

array(
        [
        
       [ 6,  3, 10,  7,  4,  6],
        
       [ 9,  2,  6, 10, 10,  7],
       
       [ 4,  3,  7,  7,  2,  5],
       
       [ 4,  1,  7,  5,  1,  4]])

       same all the time

In [76]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array5 = np.random.randint(1, 11, size=(3,7))
array5

# Find the unique numbers in the array you just created
np.unique(array5)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
# Find the 0'th index of the latest array you created
array5[0]

array([5, 3, 8, 6, 3, 1, 3])

In [79]:
# Get the first 2 rows of latest array you created
array5[:2]

array([[ 5,  3,  8,  6,  3,  1,  3],
       [ 5,  3,  1,  5, 10,  7,  7]])

In [80]:
# Get the first 2 values of the first 2 rows of the latest array
array5[:2, :2]

array([[5, 3],
       [5, 3]])

In [85]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array6 = np.random.randint(0, 11, size=(3, 5))
ones1 = np.ones((3,5))

In [89]:
# Add the two arrays together
array6 + ones1

array([[ 6.,  7.,  5.,  1.,  1.],
       [ 3.,  2.,  5., 10.,  6.],
       [ 7.,  4.,  7., 11.,  8.]])

In [90]:
# Create another array of ones of shape (5, 3)
ones2 = np.ones((5,3))

In [97]:
# Try add the array of ones and the other most recent array together
#ones1+ones2  #didn't work, because of shape 
ones2Trans = np.transpose(ones2)
ones1+ones2Trans

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [98]:
# Create another array of ones of shape (3, 5)
ones3 = np.ones((3,5))
ones3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [99]:
# Subtract the new array of ones from the other most recent array
array6-ones3

array([[ 4.,  5.,  3., -1., -1.],
       [ 1.,  0.,  3.,  8.,  4.],
       [ 5.,  2.,  5.,  9.,  6.]])

In [100]:
# Multiply the ones array with the latest array
np.multiply(array6, ones3)

array([[ 5.,  6.,  4.,  0.,  0.],
       [ 2.,  1.,  4.,  9.,  5.],
       [ 6.,  3.,  6., 10.,  7.]])

In [102]:
# Take the latest array to the power of 2 using '**'
array6**2

array([[ 25,  36,  16,   0,   0],
       [  4,   1,  16,  81,  25],
       [ 36,   9,  36, 100,  49]])

In [103]:
# Do the same thing with np.square()
np.square(array6)

array([[ 25,  36,  16,   0,   0],
       [  4,   1,  16,  81,  25],
       [ 36,   9,  36, 100,  49]])

In [104]:
# Find the mean of the latest array using np.mean()
np.mean(array6)

np.float64(4.533333333333333)

In [105]:
# Find the maximum of the latest array using np.max()
np.max(array6)

np.int64(10)

In [106]:
# Find the minimum of the latest array using np.min()
np.min(array6)

np.int64(0)

In [107]:
# Find the standard deviation of the latest array
np.std(array6)

np.float64(2.895206766747795)

In [108]:
# Find the variance of the latest array
np.var(array6)

np.float64(8.38222222222222)

In [109]:
# Reshape the latest array to (3, 5, 1)
np.reshape(array6, shape=(3,5,1))

array([[[ 5],
        [ 6],
        [ 4],
        [ 0],
        [ 0]],

       [[ 2],
        [ 1],
        [ 4],
        [ 9],
        [ 5]],

       [[ 6],
        [ 3],
        [ 6],
        [10],
        [ 7]]])

In [111]:
# Transpose the latest array
np.transpose(array6)

array([[ 5,  2,  6],
       [ 6,  1,  3],
       [ 4,  4,  6],
       [ 0,  9, 10],
       [ 0,  5,  7]])

What does the transpose do?

In [112]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1 =np.random.randint(0, 11, size=(3,3))
arr2 =np.random.randint(0, 11, size=(3,2))


In [113]:
# Perform a dot product on the two newest arrays you created
np.dot(arr1, arr2)

array([[125,  10],
       [117,  46],
       [ 75,  60]])

In [116]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr3 =np.random.randint(0, 11, size=(4, 3))
arr4 =np.random.randint(0, 11, size=(4, 3))

In [117]:
# Perform a dot product on the two newest arrays you created
np.dot(arr3, arr4) # error because of the shape 

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [118]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr3T = np.transpose(arr3)
np.dot(arr3T, arr4)

array([[ 69,  61,  31],
       [205, 156, 119],
       [ 83,  66,  29]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [123]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr5 =np.random.randint(0, 11, size=(3, 3))
arr6 =np.random.randint(0, 11, size=(3, 3))
arr5

array([[ 5,  7,  0],
       [ 7,  3, 10],
       [ 0,  7,  3]])

In [120]:
# Compare the two arrays with '>'
arr5>arr6

array([[False,  True, False],
       [False, False, False],
       [False,  True, False]])

What happens when you compare the arrays with `>`?

In [126]:
# Compare the two arrays with '>='
arr5>=arr6

array([[ True,  True, False],
       [ True, False,  True],
       [False,  True,  True]])

In [129]:
# Find which elements of the first array are greater than 7
arr5>7

array([[False, False, False],
       [False, False,  True],
       [False, False, False]])

In [131]:
# Which parts of each array are equal? (try using '==')
arr5==arr6

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [132]:
# Sort one of the arrays you just created in ascending order
np.sort(arr6)

array([[3, 5, 7],
       [2, 2, 8],
       [1, 1, 8]])

In [133]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr6)

array([[2, 0, 1],
       [0, 2, 1],
       [1, 2, 0]])

In [135]:
# Find the index with the maximum value in one of the arrays you've created
np.max(arr6)

np.int64(8)

In [136]:
# Find the index with the minimum value in one of the arrays you've created
np.min(arr6)

np.int64(1)

In [138]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr6, axis=1)

array([1, 1, 0])

In [139]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr6, axis=0)

array([1, 2, 2])

In [140]:
# Create an array of normally distributed random numbers
np.random.randn(2, 3)

array([[-2.87945689, -0.80317767, -0.00485694],
       [-0.38332331, -0.46252686, -1.11249735]])

In [141]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.