## Introduction to NumPy

NumPy were written in C. NumPy operations on arrays and lists are a lot faster than performing the same operations in Python. Avoiding loops.

In [6]:
import numpy as np

 # 1. Data types and Attributes

In [13]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [15]:
type(a1)  #ndarray is main datatype in NumPy

numpy.ndarray

In [20]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [21]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [27]:
a3.shape

(3, 2, 3)

In [31]:
a3.ndim  # number of dimensions

3

In [36]:
# Create a FataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

,0,1,2
0,1.0,2.0,3.3
1,4.0,5.0,6.5


## 2. Creating a numPy arrays

In [38]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [39]:
sample_array.dtype

dtype('int64')

In [46]:
ones = np.ones((2, 3), dtype='int64', order='C')    # shift + tab  ---> gives an instruction how to use function
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [48]:
zeroes = np.zeros((2, 3), dtype='int64', order='C')
zeroes

array([[0, 0, 0],
       [0, 0, 0]])

In [51]:
# range array 
range_array = np.arange(1, 25, 3)
range_array

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [68]:
# Random array - wypisuje randomowe inty od 1 do 20 (5 liczb)
random_array = np.random.randint(1, 20, 5)
random_array

# Macierz 
random_arr = np.random.randint(1, 20, size=(10,15))
random_arr


array([[17, 17,  4,  2, 18, 17, 11, 19, 12,  8, 17,  8, 15, 16,  9],
       [ 2, 17, 13,  9, 18,  6,  1, 15,  3,  1,  7,  6,  3, 15,  4],
       [ 9, 15,  7, 14, 13, 11, 13,  5, 19, 17, 13,  4, 16,  1,  5],
       [19,  7,  7, 19, 19,  8, 15, 10, 13, 11,  7, 17, 17, 18, 18],
       [ 1,  7,  6,  9, 17, 15,  5, 17, 17, 13,  6, 15,  2, 13, 19],
       [ 7, 12,  1, 12, 15,  6, 18, 10, 10,  6, 14,  1,  1,  8, 12],
       [ 9,  6, 11,  4,  9, 15, 17, 18,  3,  9, 17,  2,  6, 13, 17],
       [16,  6,  2,  8,  4, 18, 14,  8,  5, 13, 15, 14, 16,  6, 10],
       [ 6,  4, 13,  5,  7, 11,  3,  9, 12, 11, 13, 16,  1,  9, 11],
       [13, 14, 12, 16,  2,  9,  2, 16,  1, 13,  6,  6,  7, 11, 19]])

In [70]:
# Rozmiar randomowej macierzy 
random_arr.size

150

In [74]:
# Returning random floats 
np.random.random((5,5))

array([[0.94465125, 0.92610991, 0.57510655, 0.98175366, 0.99683189],
       [0.04114602, 0.11861453, 0.51157209, 0.36553551, 0.47622466],
       [0.06211206, 0.1646395 , 0.45357419, 0.27277453, 0.03640252],
       [0.36570534, 0.61330788, 0.70776766, 0.25470511, 0.51219027],
       [0.98576135, 0.32721271, 0.04311954, 0.55334036, 0.01605794]])

# Random Seed

In [95]:
# Pseudo random numbers - still generate random numbers, but random niumbers that are reproducible
np.random.seed(seed=42)   #jak zakomentujesz i zabierzesz seep w nawiasach to liczby będa inne 
randomSeed = np.random.randint(10, size=(5,3))
randomSeed

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])